# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

return unless location.pathname == '/'

twttr.ready (twttr) ->
  twttr.events.bind 'rendered', (event) ->
    $el = $(event.target)
    if $el.hasClass('.twitter-tweet-error')
      $el.css display: 'none'
    else
      $el.css display: 'inline-block'

$ ->
  $('a').click (e) ->
    e.preventDefault()
    href = $(e.target).attr('href')
    return if !href

    offset = $('nav').height() - 2

    $('html, body').animate { scrollTop: $(href).offset().top - offset }, 500

  window.toggleSync = ->
    $('i').toggleClass 'stop'


# ---
# generated by js2coffee 2.2.0
